### ISSUE TITLE
[EasyLang] Create two branded logo for "Extension" and "Context-Tutor"

### ISSUE THREAD

**Issue by NadiaZu** [easably/RoadMap#10]
- [x] Tutor logo
- [x] extension logo
- [x] chrome web store logo

**Comment by lizakostyushkina** [comment]
https://www.figma.com/file/3Ge6ogvelWBJ2caGsDLygQ/logo-for-Extension-and-Context-Tutor?node-id=163%3A0

Frame 39 - Tutor
Frame 43 - Extension

**Comment by lizakostyushkina** [comment]
- [ ] Update strokes
- [ ] Make Round logos in vector @annamaksimik 

![image](https://user-images.githubusercontent.com/58728395/71763035-3124b100-2ee8-11ea-980f-ac0000ce112e.png)
![image](https://user-images.githubusercontent.com/58728395/71763046-50bbd980-2ee8-11ea-8735-0ec564054fad.png)

**Comment by lizakostyushkina** [comment]
![image](https://user-images.githubusercontent.com/58728395/71974089-ab736f00-3221-11ea-97a1-6b881375ec7f.png)
@annamaksimik

**Comment by annamaksimik** [comment]
Сейчас посмотрю, должен быть одинаковый и угол и высота, уже поправляю
