### ISSUE TITLE
Add back arrow to forgot password window

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/RoadMap#42]
![338CAED7-8B7B-4BEE-A858-42AFED07D216](https://user-images.githubusercontent.com/63041847/82659377-44cf7a80-9c31-11ea-8984-b4c56e2cf3b9.jpeg)

**Comment by annamaksimik** [comment]
![image](https://user-images.githubusercontent.com/58423687/82659940-23bb5980-9c32-11ea-83d0-54c6f7b840c4.png)
