### ISSUE TITLE
Make youtube link 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/RoadMap#61]
In the first step there is no link to youtube 
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=808%3A252

**Comment by annamaksimik** [comment]
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=946%3A140

**Comment by KatyaLogosh** [comment]
> https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=946%3A140

Maybe its better to make it "Голубее"?:)

**Comment by KatyaLogosh** [comment]
> https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=946%3A140

@6alex6kash6

**Comment by KatyaLogosh** [comment]
https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/Player?node-id=965%3A37
@6alex6kash6
