### ISSUE TITLE
Make the design of listening 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/RoadMap#75]
![80109C6C-54E2-4A9A-B0A3-355FAFE9C27B](https://user-images.githubusercontent.com/63041847/83759217-ea480c80-a67b-11ea-9aa8-fb14ec665f33.png)

**Comment by annamaksimik** [comment]
https://www.figma.com/file/biat2pS2aaqXtNGXLxnK3x/Games-Desktop?node-id=259%3A1805
